function OceanTempRiseData() {
  return (
    <div>
      <h1>Ocean Temperature Rise General Information</h1>
      <p>
        Ocean temperature rise refers to the long-term increase in the
        temperature of the world's oceans due to the buildup of greenhouse gases
        in the atmosphere. The oceans absorb over 90% of the excess heat trapped
        by human-caused global warming, making ocean warming one of the
        strongest indicators of climate change.
      </p>
      <h2>What Is Happening?</h2>
      <p>
        The global ocean has been warming continuously since at least the 1970s.
        Sea surface temperatures have increased by about 0.88°C between
        1850–1900 and 2011–2020. Ocean warming is occurring from the surface to
        depths greater than 2,000 meters, with even the deep ocean showing
        measurable warming. Marine heatwaves have become approximately twice as
        frequent since the 1980s and are becoming longer and more intense.
      </p>
      <h2>What Does the Evidence Show?</h2>
      <p>
        Scientists have collected evidence from satellites, ships, buoys, and
        autonomous Argo floats that consistently shows: The ocean has absorbed
        about 90% of the excess heat generated by human-caused climate change
        since the 1970s. Ocean heat content has reached record highs in recent
        decades. The rate of ocean warming has accelerated since the 1990s.
        Human influence is extremely likely to be the main cause of recent ocean
        warming, according to the Intergovernmental Panel on Climate Change
        (IPCC).
      </p>
      <h2>Why Does It Matter?</h2>
      <p>
        Rising ocean temperatures have widespread impacts on Earth's climate and
        ecosystems, including: Sea-level rise: Warmer water expands,
        contributing to rising sea levels. More extreme weather: Warmer oceans
        provide more energy for stronger hurricanes, tropical storms, and heavy
        rainfall. Marine ecosystem damage: Coral reefs experience bleaching,
        while many marine species are forced to migrate or face population
        declines. Reduced oxygen levels: Warmer water holds less oxygen,
        stressing marine life. Changes in fisheries: Fish populations shift,
        affecting food security and coastal economies. More frequent marine
        heatwaves: These events can cause mass die-offs of corals, kelp forests,
        shellfish, and other marine organisms.
      </p>
      <h2>Sources</h2>
      <p>
        Intergovernmental Panel on Climate Change (IPCC). Climate Change 2021:
        The Physical Science Basis – Chapter 9: Ocean, Cryosphere and Sea Level
        Change. I IPCC IPCC. Technical Summary – Climate Change 2021: The
        Physical Science Basis. I IPCC IPCC. Chapter 2: Changing State of the
        Climate System. I IPCC IPCC. Special Report on the Ocean and Cryosphere
        in a Changing Climate (SROCC). I IPCC NOAA Ocean Acidification Program.
        An Overview of Ocean Climate Change Indicators. O
        oceanacidification.noaa.gov NOAA Climate.gov. Climate Change: Global
        Temperature. C climate.gov
      </p>
    </div>
  );
}

export default OceanTempRiseData;
